name: aerocast
description: A waether app.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  google_fonts:  ^5.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
